repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--strict, --config-file=.yamllint.yaml]
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: shellcheck
  - repo: https://github.com/jtyr/kubeconform-helm
    rev: v0.2.0
    hooks:
      - id: kubeconform-helm
        args:
          - --charts-path=platform
          - --strict
          - --summary
          - --verbose
          - --schema-location=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json
          - --schema-location=default
          - --ignore-missing-schemas
        files: ^(platform)/
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        description: Run golangci-lint linter
        language: system
        types: [go]
        pass_filenames: false
      - id: ct-lint
        name: ct-lint
        entry: ct lint
        description: Run ct lint
        language: system
        types: [yaml]
        pass_filenames: false
