argo-cd:
  # -- Globally shared configuration
  global:
    # -- Node selector for all components
    nodeSelector:
      tier: internal

  spec:
    destination:
      server: https://kubernetes.default.svc
    project: platform
    source:
      path: platform/platform/argocd
      repoURL: https://github.com/wallchristopher/platform
      targetRevision: HEAD
